trigger:
  - release

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_12_x:
      node_version: 12.x

variables:
  app: /home/web/client
steps:
  - task: Npm@1
    displayName: 安装依赖
    inputs:
      command: install
      customRegistry: useNpmrc
  - script: npm run build
    displayName: 打包

  - task: CopyFilesOverSSH@0
    displayName: 上传文件
    inputs:
      sshEndpoint: samurai
      sourceFolder: dist
      contents: '**'
      targetFolder: $(app)
      cleanTargetFolder: true
